apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  selector:
    app: redis-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
